### ISSUE TITLE
[Feature request] Add autocomplete for binary names when execute-assembly path was defined

### ISSUE THREAD

**Issue by 0xShkk** [mgeeky/cobalt-arsenal#1]
Hi,

thank you for this great addon to Cobaltstrike.
Your collection makes working with CS way less painfull!

I wanted to ask, if it is possible to add autocomplete for your redefined execute-assembly function?
For example, when I have defined my assembly path for execute-assembly to lookup the binaries and I want to run Seatbelt.exe I do

```
execute-assembly Seatbelt.exe
```
Is it possible to add support for pressing `TAB` after entering `execute-assembly Sea` ?

**Comment by mgeeky** [comment]
Hi,

I've been looking into this myself some time ago out of the same desire but couldnt find required agressor API (Sleep) to accomodate this. For the time being, I've no idea how to implement this so unfortunately there's nothing I can do at the moment.

Hope that addressew your request.

Regards, 
Mariusz.
